version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
